/**
 * Token build. Reads tokens.source.json and emits every consumable format.
 *
 * This is the direction of flow that makes the system functional: values are
 * declared once here and generated outward. Nothing downstream, including the
 * brand book page, may declare a colour of its own.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(join(ROOT, 'tokens/tokens.source.json'), 'utf8'));
const { primitives, aliases, typeRoles, breakpoints, layout, gradients = [] } = src;

const byGroup = (g) => primitives.filter((t) => t.group === g);
const valueOf = (name) => primitives.find((t) => t.name === name)?.value ?? name;

/** A semi-transparent alias becomes a color-mix so it stays a live reference. */
const aliasValue = ({ ref, alpha }) => {
  const isHex = ref.startsWith('#');
  const base = isHex ? ref : `var(--color-${ref})`;
  if (alpha >= 1) return base;
  return `color-mix(in srgb, ${base} ${Math.round(alpha * 100)}%, transparent)`;
};

/**
 * Type roles are declared as ranges ("16-20px", "145%", "-1%") because that is
 * how the brand book states them. CSS needs real values, so a range becomes a
 * fluid clamp() interpolated between the sm and xl breakpoints, a percentage
 * line height becomes a unitless ratio, and a percentage track becomes em.
 */
const FLUID_MIN = 620;
const FLUID_MAX = 1200;

const fluidSize = (range) => {
  const m = String(range).match(/^(\d+(?:\.\d+)?)-(\d+(?:\.\d+)?)px$/);
  if (!m) return range;
  const [min, max] = [Number(m[1]), Number(m[2])];
  const slope = (max - min) / (FLUID_MAX - FLUID_MIN);
  const intercept = min - slope * FLUID_MIN;
  return `clamp(${min}px, ${round(intercept)}px + ${round(slope * 100)}vw, ${max}px)`;
};

const ratio = (pct) => {
  const m = String(pct).match(/^(-?\d+(?:\.\d+)?)%$/);
  return m ? round(Number(m[1]) / 100) : pct;
};

const em = (pct) => {
  const m = String(pct).match(/^([+-]?\d+(?:\.\d+)?)%$/);
  return m ? `${round(Number(m[1]) / 100)}em` : pct;
};

function round(n) {
  return Math.round(n * 1000) / 1000;
}

const banner = (title) =>
  `/* ${title}\n * Generated by tokens/build.mjs from tokens/tokens.source.json.\n * Do not edit by hand: run \`npm run build:tokens\`.\n * Assembly brand system v${src.$meta.version}\n */`;

/* ── CSS custom properties ──────────────────────────────────────────────── */
const buildCss = () => {
  const L = [banner('Assembly design tokens'), '', ':root {'];
  for (const g of ['color', 'radius', 'space', 'font']) {
    L.push(`  /* ${g} */`);
    for (const t of byGroup(g)) {
      const name = g === 'color' ? `--color-${t.name}` : `--${t.name}`;
      L.push(`  ${name}: ${t.value};${t.use ? ` /* ${t.use} */` : ''}`);
    }
    L.push('');
  }
  L.push('  /* layout */');
  for (const t of layout) L.push(`  --${t.name}: ${t.value};${t.use ? ` /* ${t.use} */` : ''}`);
  L.push('', '  /* gradients */');
  for (const g of gradients) L.push(`  --${g.name}: ${g.value};${g.use ? ` /* ${g.use} */` : ''}`);
  L.push('', '  /* semantic aliases, light */');
  for (const a of aliases) {
    L.push(`  --${a.name}: ${aliasValue(a.light)};${a.conflict ? ' /* [Conflict] see knowledge/conflicts.md */' : ''}`);
  }
  L.push('}', '');

  const darkBlock = aliases.map((a) => `  --${a.name}: ${aliasValue(a.dark)};`).join('\n');
  L.push('/* Dark theme. Opt in with data-theme="dark", or follow the system. */');
  L.push('[data-theme="dark"] {', darkBlock, '}', '');
  L.push('@media (prefers-color-scheme: dark) {');
  L.push('  :root:not([data-theme="light"]) {');
  L.push(darkBlock.split('\n').map((l) => '  ' + l).join('\n'));
  L.push('  }', '}', '');

  L.push('/* Type roles. Sizes are fluid between the sm and xl breakpoints. */', ':root {');
  for (const t of typeRoles) {
    L.push(`  /* ${t.name}: ${t.size}, ${t.line} line, ${t.track} tracking, ${t.weight} */`);
    L.push(`  --${t.name}-size: ${fluidSize(t.size)};`);
    L.push(`  --${t.name}-line: ${ratio(t.line)};`);
    L.push(`  --${t.name}-track: ${em(t.track)};`);
    L.push(`  --${t.name}-weight: ${t.weight};`);
  }
  L.push('}', '');

  L.push('/* breakpoints, for reference. Media queries cannot read custom properties. */');
  L.push(':root {');
  for (const b of breakpoints) L.push(`  --breakpoint-${b.name}: ${b.value};${b.use ? ` /* ${b.use} */` : ''}`);
  L.push('}');
  return L.join('\n') + '\n';
};

/* ── W3C DTCG JSON ──────────────────────────────────────────────────────── */
const buildJson = () => {
  const out = {
    $description: src.$meta.description,
    color: {}, radius: {}, space: {}, font: {},
    semantic: { light: {}, dark: {} },
    type: {}, breakpoint: {}, layout: {}, gradient: {}
  };
  for (const t of primitives) {
    const $type = t.group === 'color' ? 'color' : t.group === 'font' ? 'fontFamily' : 'dimension';
    out[t.group][t.name] = {
      $type, $value: t.value,
      ...(t.use ? { $description: t.use } : {}),
      $extensions: { 'cloud.assembly': { status: t.status } }
    };
  }
  for (const a of aliases) {
    for (const mode of ['light', 'dark']) {
      const v = a[mode];
      out.semantic[mode][a.name] = {
        $type: 'color',
        $value: v.ref.startsWith('#') ? v.ref : `{color.${v.ref}}`,
        $description: a.intent,
        $extensions: {
          'cloud.assembly': {
            status: v.status,
            ...(v.alpha < 1 ? { alpha: v.alpha } : {}),
            ...(a.conflict?.[mode] ? { conflict: a.conflict[mode] } : {})
          }
        }
      };
    }
  }
  for (const t of typeRoles) {
    out.type[t.name] = {
      $type: 'typography',
      $value: {
        fontFamily: '{font.font-brand}',
        fontSize: t.size, lineHeight: t.line,
        letterSpacing: t.track, fontWeight: t.weight
      }
    };
  }
  for (const b of breakpoints) out.breakpoint[b.name] = { $type: 'dimension', $value: b.value, $description: b.use };
  for (const l of layout) out.layout[l.name] = { $value: l.value, $description: l.use };
  for (const g of gradients) {
    out.gradient[g.name] = {
      $type: 'gradient',
      $value: g.value,
      $description: g.use,
      $extensions: { 'cloud.assembly': { status: g.status, ...(g.note ? { note: g.note } : {}) } }
    };
  }
  return JSON.stringify(out, null, 2) + '\n';
};

/* ── Tailwind v4 theme ──────────────────────────────────────────────────── */
const buildTailwind = () => {
  const L = ['@import "tailwindcss";', '', banner('Assembly Tailwind v4 theme'), '', '@theme {'];
  for (const t of byGroup('color')) L.push(`  --color-${t.name}: ${t.value};`);
  L.push('');
  for (const t of byGroup('radius')) L.push(`  --${t.name}: ${t.value};`);
  L.push('');
  for (const t of byGroup('space')) L.push(`  --spacing-${t.name.replace('space-', '')}: ${t.value};`);
  L.push('');
  for (const t of byGroup('font')) L.push(`  --${t.name}: ${t.value};`);
  L.push('');
  for (const b of breakpoints) L.push(`  --breakpoint-${b.name}: ${b.value};`);
  L.push('}', '', '@layer base {', '  :root {');
  for (const a of aliases) L.push(`    --${a.name}: ${aliasValue(a.light)};`);
  L.push('  }', '', '  [data-theme="dark"] {');
  for (const a of aliases) L.push(`    --${a.name}: ${aliasValue(a.dark)};`);
  L.push('  }', '}');
  return L.join('\n') + '\n';
};

/* ── Figma variables ────────────────────────────────────────────────────── */
const buildFigma = () => JSON.stringify({
  $meta: { generatedFrom: 'tokens/tokens.source.json', version: src.$meta.version },
  collections: [
    {
      name: 'Primitives',
      modes: ['Value'],
      variables: primitives.map((t) => ({
        name: `${t.group}/${t.name}`,
        type: t.group === 'color' ? 'COLOR' : t.group === 'font' ? 'STRING' : 'FLOAT',
        valuesByMode: {
          Value: t.group === 'color' || t.group === 'font' ? t.value : parseFloat(t.value)
        },
        ...(t.use ? { description: t.use } : {})
      }))
    },
    {
      name: 'Semantic',
      modes: ['Light', 'Dark'],
      variables: aliases.map((a) => ({
        name: `alias/${a.name}`,
        type: 'COLOR',
        description: a.intent + (a.conflict ? ' [Conflict: see knowledge/conflicts.md]' : ''),
        valuesByMode: {
          Light: { alias: `color/${a.light.ref}`, resolved: valueOf(a.light.ref), opacity: a.light.alpha },
          Dark: { alias: `color/${a.dark.ref}`, resolved: valueOf(a.dark.ref), opacity: a.dark.alpha }
        }
      }))
    }
  ]
}, null, 2) + '\n';

/* ── Write ──────────────────────────────────────────────────────────────── */
mkdirSync(join(ROOT, 'dist'), { recursive: true });
const outputs = {
  'dist/tokens.css': buildCss(),
  'dist/tokens.json': buildJson(),
  'dist/theme.css': buildTailwind(),
  'dist/figma-variables.json': buildFigma()
};
for (const [file, body] of Object.entries(outputs)) {
  writeFileSync(join(ROOT, file), body);
  console.log(`  ${file.padEnd(28)} ${String(body.split('\n').length - 1).padStart(4)} lines`);
}
const conflicts = aliases.filter((a) => a.conflict).length;
console.log(`\n  ${primitives.length} primitives, ${aliases.length} aliases, ${typeRoles.length} type roles`);
if (conflicts) console.log(`  ${conflicts} aliases carry an unresolved [Conflict]. See knowledge/conflicts.md`);
